// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIyszsnMc2Gc31sq45tSWwxtdi48eqObc',
    appId: '1:371170387063:android:3daa807dfe09d994a05272',
    messagingSenderId: '371170387063',
    projectId: 'safrah-9fd11',
    storageBucket: 'safrah-9fd11.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYCKzAbkEozj1KfMhmMXNCSFtC1Xn0ht0',
    appId: '1:371170387063:ios:ab34ce1e60dbace2a05272',
    messagingSenderId: '371170387063',
    projectId: 'safrah-9fd11',
    storageBucket: 'safrah-9fd11.firebasestorage.app',
    iosBundleId: 'com.example.safraaPassengerApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO2MDRqToZKU6cGOjc5EiBlXDJfZEetBw',
    appId: '1:371170387063:web:4201fadc03b9842da05272',
    messagingSenderId: '371170387063',
    projectId: 'safrah-9fd11',
    authDomain: 'safrah-9fd11.firebaseapp.com',
    storageBucket: 'safrah-9fd11.firebasestorage.app',
    measurementId: 'G-VMZFSQBNWS',
  );
}
